---
- name: Create a directory for picool if it does not exist
  ansible.builtin.file:
    path: /home/ansible/git/picool
    state: directory
    mode: '0755'
  become: false
- name: Check out the Picool repo
  ansible.builtin.git:
    repo: https://github.com/Smithsonite/picool.git
    dest: /home/ansible/git/picool
    version: main
  become: false

- name: Install python pip globally
  ansible.builtin.apt:
    name: python3-pip
    state: present

- name: Copy fancontrol files
  ansible.builtin.copy:
    remote_src: "{{ item.remote_src }}"
    dest: "{{ item.dest }}"
    owner: root
    group: root
    mode: u=rwxr,g=r,o=x
  with_items:
    - remote_src: /home/ansible/git/picool/fancontrol.py
      dest: /usr/local/bin/fancontrol.py
    - remote_src: /home/ansible/git/picool/requirements.txt
      dest: /home/ansible/picool/
    - remote_src: /home/ansible/git/picool/fancontrol.sh
      dest: /etc/init.d/fancontrol.sh

- name: Install picool requirements
  ansible.builtin.pip:
    requirements: /home/ansible/picool/requirements.txt

- name: Enabling the picool service
  ansible.builtin.service:
    name: fancontrol.sh
    enabled: true

- name: Unconditionally reboot the machine with all defaults
  ansible.builtin.reboot:
