name: Release

on:
  push:
    branches: [ "main" ]

  workflow_dispatch:

env:
  GH_TOKEN: ${{ github.token }}

jobs:
  deploy_release:
    uses: smithsonite/RequiredWorkflows/.github/workflows/ansible_release.yml@main
    secrets: inherit
    